### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by roks0n**
## Proposed changes

Merge develop branch into master. Along with this change, the default branch can be set to `master` for this repo.

## Types of changes

What types of changes does your code introduce?
- [x] Other: merged develop branch into master

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/docs/contributing) documentation

### CODE REVIEW

**Comment by faustbrian** [comment]
I will test it tomorrow and merge if everything works as expected and follows the guidelines.

**Comment by roks0n** [comment]
cool 👍please note that I've created an issue for identity-related functionalities (PrivateKey, PublicKey, Address, WIF) to align them more with other crypto libraries.

**Comment by faustbrian** [comment]
That should be done before I merge because the initial release will be tagged once it is merged to master.

**Comment by roks0n** [comment]
I'll close this PR for now until I resolve everything.

**Pull request closed without merging**
